[template variables=DATASETS]
description=List of datasets available for processing
help=This workflow allows you to retrieve the following datasets:
    =
    = * alpha - tell us something about alpha
    = * beta - tell us something about beta
    = * gamma - tell us something about gamma
length=:
values="alpha","beta","gamma"
value-hints=alpha,beta,gamma
sort-key=

[template variables=ALPHA]
description=Turn on Alpha dataset.
           =This dataset contains information about alpha.
type=boolean

[template variables=BETA]
description=Turn on Beta dataset.
help=This dataset contains information about beta.
type=boolean

[template variables=GAMMA]
description=Turn on Gamma dataset.
help=This dataset contains information about gamma.
type=boolean
