name: Cylc Checks

on:
  push:
    branches: [master, cylc-8]
  pull_request:
    branches: [master, cylc-8]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cylc-flow
          
      - name: Checking workflow with Cylc Lint
        run: |
          cylc lint --color=always ./simplest

      - name: Checking workflow with Cylc Lint
        run: |
          cylc validate --color=always ./simplest
